Repository BrightCoders-Institute/BCDIC22-RN-proyecto-final-team1, pull requests merged in 2023-03, with the labels that each got.

#30 Feature#15-Handle-inpit-change
  package-lock.json
  src/components/TextInputHandle.jsx
  src/components/TextInputPass.jsx
  src/themes/CardStyle.jsx
  src/themes/SignUpStyle.jsx
  src/views/LoginScreen.jsx
  src/views/SignUpScreen.jsx
Labels: @GaddPat0609

#32 Feature#16-Firebase-config
  .gitignore
  Firebase.config.js
  package-lock.json
  package.json
  src/components/TextInputHandle.jsx
Labels: @GaddPat0609

#35 Feature#18-MarkMap
  src/views/AddRecord.jsx
Labels: @victordoom

#40 Feature#21-Reported-damages-admin-screen
  App.js
  src/themes/ReportedDamageStyle.jsx
  src/views/ReportedDamages.jsx
Labels: @victordoom

#43 Feature#19-User-data-drawer-menu
  src/api/firebase.jsx
  src/navigation/index.jsx
  src/views/LoginScreen.jsx
Labels: @victordoom

#42 Feature #20 Admin detail view design
  App.js
  Firebase.config.js
  src/components/ButtonGreen.jsx
  src/themes/ButtonStyle.jsx
  src/themes/colors.jsx
  src/views/AdminDetails.jsx
Labels: @victordoom

#45 Feature#22 add damage records
  app.json
  package-lock.json
  package.json
  src/api/firebase.jsx
  src/navigation/index.jsx
  src/themes/AddRecordStyle.jsx
  src/themes/colors.jsx
  src/views/AddRecord.jsx
Labels: @Zuack55

#48 Feature#24-See-reports-user
  src/components/Cards.jsx
  src/views/LoginScreen.jsx
  src/views/MyRecords.jsx
Labels: @Leonardo-Aguirre-Ponce

#47 Feature#23 textinput validation
  Firebase.config.js
  babel.config.js
  package-lock.json
  package.json
  src/api/firebase.js
  src/components/TextInputHandle.jsx
  src/components/TextInputPass.jsx
  src/navigation/index.jsx
  src/themes/AddRecordStyle.jsx
  src/themes/StartupStyle.jsx
  src/themes/colors.jsx
  src/views/LoginScreen.jsx
  src/views/SignUpScreen.jsx
  src/views/StartupScreen.jsx
Labels: @Leonardo-Aguirre-Ponce
